# Made by JeongWonPark (appletreegood@naver.com)

# Environment
# https://pgtune.leopard.in.ua/#/

FROM postgres:14.1

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD postgres

# DB Version: 14
# OS Type: mac
# DB Type: dw
# Total Memory (RAM): 20 GB
# Data Storage: ssd

ENV max_connections = 40
ENV shared_buffers = 512MB
ENV effective_cache_size = 1536MB
ENV maintenance_work_mem = 256MG
ENV checkpoint_ completion_target = 0.9
ENV wal_buffers = 16MB
ENV default_statistics_target = 500
ENV random_page_cost = 1.1
ENV work_mem = 3276KB
ENV min_wal_size = 4GB
ENV max_wal_size = 16GB

ENV TZ = "Asia/Seoul"

EXPOSE 5432
